/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Swagger API
 * This is a swagger for API.
 * OpenAPI spec version: 1.0
 */
import { rest } from 'msw'
import { faker } from '@faker-js/faker'

export const getLoginMock = () => ({
  data: {
    accessToken: (() => faker.string.nanoid())(),
    email: (() => 'demo@dwarves.foundation')(),
    id: (() => 2)(),
  },
})

export const getSignupMock = () => ({ data: { message: faker.random.word() } })

export const getAuthMSW = () => [
  rest.post('*/portal/auth/login', (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, 'Mocked status'),
      ctx.json(getLoginMock()),
    )
  }),
  rest.post('*/portal/auth/signup', (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, 'Mocked status'),
      ctx.json(getSignupMock()),
    )
  }),
]
