/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * FE-23 OpenAI API
 * OpenAPI spec version: 1.0.0
 */
import type { LoginResponse, LoginRequest } from '../model'
import { requester } from '../mutator/requester'

/**
 * Login to by Discord username (listed on Google Sheets)
 * @summary Login
 */
export const login = (loginRequest: LoginRequest) => {
  return requester<LoginResponse>({
    url: `/auth/login`,
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    data: loginRequest,
  })
}
