extends: '@ibm-cloud/openapi-ruleset'
rules:
  schema-description: off
  ibm-property-casing-convention:
    description: "Property names must follow camel case"
    message: "{{error}}"
    resolved: true
    given: schemas
    severity: "error"
    then:
      function: propertyCasingConvention
      functionOptions:
        type: "camel"
  ibm-path-segment-casing-convention:
    description: "Path segments must follow camel case"
    message: "{{error}}"
    formats: [oas3]
    given: paths
    severity: "error"
    then:
      function: pathSegmentCasingConvention
      functionOptions:
        type: "camel"
