/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * FE-23 OpenAI API
 * OpenAPI spec version: 1.0.0
 */
import type {
  OpenAIResponse,
  OpenAIRequest,
  GetChatCompletionsParams,
} from '../model'
import { requester } from '../mutator/requester'

/**
 * Given a list of messages comprising a conversation, the model will return a response.
 * @summary Completions
 */
export const getChatCompletions = (
  openAIRequest: OpenAIRequest,
  params?: GetChatCompletionsParams,
) => {
  return requester<OpenAIResponse>({
    url: `/chat/completions`,
    method: 'post',
    headers: {
      'Content-Type': 'application/json',
    },
    data: openAIRequest,
    params,
  })
}
