/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Swagger API
 * This is a swagger for API.
 * OpenAPI spec version: 1.0
 */

export type GetUsersListParams = {
  /**
   * Page
   */
  page?: number
  /**
   * Page size
   */
  pageSize?: number
}
