/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * FE-23 OpenAI API
 * OpenAPI spec version: 1.0.0
 */

export interface LoginResponseData {
  id: number
  username: string
  accessToken: string
}
