/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Swagger API
 * This is a swagger for API.
 * OpenAPI spec version: 1.0
 */
import type { Auth } from './auth'

export interface LoginResponse {
  data?: Auth
}
