/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * FE-23 OpenAI API
 * OpenAPI spec version: 1.0.0
 */
import type { OpenAIRequestFunctionCallAnyOf } from './openAIRequestFunctionCallAnyOf'

export type OpenAIRequestFunctionCall = string | OpenAIRequestFunctionCallAnyOf
