/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * FE-23 OpenAI API
 * OpenAPI spec version: 1.0.0
 */
import type { OpenAIMessage } from './openAIMessage'
import type { OpenAIFunction } from './openAIFunction'
import type { OpenAIRequestFunctionCall } from './openAIRequestFunctionCall'
import type { OpenAIRequestLogitBias } from './openAIRequestLogitBias'

export interface OpenAIRequest {
  model?: string
  messages: OpenAIMessage[]
  functions?: OpenAIFunction[]
  functionCall?: OpenAIRequestFunctionCall
  temperature?: number
  topP?: number
  n?: number
  stream?: boolean
  stop?: string
  maxTokens?: number
  presencePenalty?: number
  frequencyPenalty?: number
  logitBias?: OpenAIRequestLogitBias
  user?: string
  transforms?: string[]
  appUrl?: string
  appName?: string
}
