/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * FE-23 OpenAI API
 * OpenAPI spec version: 1.0.0
 */
import type { OpenAIChoice } from './openAIChoice'
import type { OpenAIUsage } from './openAIUsage'

export interface OpenAIResponse {
  data: OpenAIResponse
  choices: OpenAIChoice[]
  model: string
  usage: OpenAIUsage
  id: string
}
