/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Swagger API
 * This is a swagger for API.
 * OpenAPI spec version: 1.0
 */

export interface User {
  avatar: string
  department: string
  email: string
  fullName: string
  id: number
  role: string
  status: string
  title: string
}
